[tool.poetry]
name = "project-template"
version = "0.1.0"
description = ""
authors = ["John Doe <jhon.doe.com>"]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"